Diagnosing the paralell ability of the current quasse function
========================================================

Load package and seed some random parameters.
```{r}
require(diversitree)
lambda <- function(x) sigmoid.x(x, 0.1, 0.2, 0, 2.5)
mu <- function(x) constant.x(x, 0.03)
char <- make.brownian.with.drift(0, 0.025)
```

Create a phylogeny

```{r fig.width=7, fig.height=6}
set.seed(1)
phy <- tree.quasse(c(lambda, mu, char), max.taxa=15, x0=0,
single.lineage=FALSE)
plot(phy)
```

Create a no drift model

```{r}
states <- phy$tip.state
states.sd <- 1/200
lik <- make.quasse(phy, states, states.sd, sigmoid.x, constant.x)
lik.nodrift <- constrain(lik, drift ~ 0)
argnames(lik.nodrift)
```

Evaluate the function once
```{r}
#provide pars
pars <- c(.1, .2, 0, 2.5, .03, .01)

lik.nodrift(pars)
```

Can we call the function in parallel? Not even optim(), just call the exact same function in multiple instances of R. 

```{r,results='asis'}

require(foreach)
require(doSNOW)

cl<-makeCluster(2,"SOCK")
registerDoSNOW(cl)
foreach(i=1:5) %dopar%{
  lik.nodrift(pars)
}
```

I've never seen a function with this behavior before. 
